services:
  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: /bin/bash -c /code/startup.sh
    volumes:
      - ./code/:/code
    ports:
      - "8000:8000"
    env_file:
      - ./docker/django/.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres:16.3
#    build:
#      context: .
#      dockerfile: docker/postgres/Dockerfile
    volumes:
      - ./postgres/setup/:/docker-entrypoint-initdb.d
      - ./postgres_data/:/var/lib/postgresql/postgres_data/
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
    ports:
      - "5432:5432"
volumes:
  postgres_data: